name: Application Deployment

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/application.yml'
      - '.github/workflows/deploy-azure.yml'
      - 'AzureWorkshop/**'
      - 'AzureWorkshopTest/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/application.yml'
      - 'AzureWorkshop/**'
      - 'AzureWorkshopTest/**'
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'test'
      webapp_var_name: ${{ vars.AZURE_WEBAPP_NAME }}
    secrets: inherit
  deploy-production:
    needs: deploy-test
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'production'
      webapp_var_name: ${{ vars.AZURE_WEBAPP_NAME }}
    secrets: inherit
