name: Application Deployment

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/application.yml'
      - 'AzureWorkshop/**'
      - 'AzureWorkshopTest/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/application.yml'
      - 'AzureWorkshop/**'
      - 'AzureWorkshopTest/**'
  workflow_dispatch:

jobs:
  deploy-test:
    permissions:
      contents: read
      id-token: write
      actions: read
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'test'
      webapp_secret_name: 'TEST_WEBAPP_NAME'
    secrets: inherit

  deploy-production:
    permissions:
      contents: read
      id-token: write
      actions: read
    needs: deploy-test
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'production'
      webapp_secret_name: 'WEBAPP_NAME'
    secrets: inherit
