name: Application Deployment

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/application.yml'
      - 'AzureWorkshop/**'
      - 'AzureWorkshopTest/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/application.yml'
      - 'AzureWorkshop/**'
      - 'AzureWorkshopTest/**'
  workflow_dispatch:
    
permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  publish-test:
    uses: ./.github/workflows/build-app.yml
    with:
      releasetype: 'test'
    secrets: inherit
    
  # publish-production:
  #   needs: publish-test
  #   uses: ./.github/workflows/deploy-azure.yml
  #   with:
  #     releasetype: 'production'
  #   secrets: inherit

  deploy:
    needs: publish-test
    uses: ./.github/workflows/deploy-to-azure.yml
    with:
      releasetype: 'test'
    secrets: inherit