name: Application Deployment

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/application.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/application.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'test'
      webapp_secret_name: 'TEST_WEBAPP_NAME'
    secrets: inherit

  deploy-production:
    needs: deploy-test
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'production'
      webapp_secret_name: 'WEBAPP_NAME'
    secrets: inherit