name: IaC bicep validate

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT_NAME: 'TEST'
  AZURE_LOCATION: 'norwayeast'
  RESOURCE_GROUP_NAME: 'rg-azskolen-test'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
    validate-bicep:
      name: Validate Bicep
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Bicep lint
          uses: azure/cli@v1
          with:
            inlineScript: |
              set -e
              echo "Running Bicep build..."
              az bicep build --file bicep/main.bicep
              echo "Running Bicep lint..."
              az bicep lint --file bicep/main.bicep

        - name: Bicep Validate
          if: success()
          uses: Azure/cli@v1
          with:
            inlineScript: |
              set -e
              echo "Validating Bicep template..."
              az deployment group validate \
                --name validate-${{ github.run_id }} \
                --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
                --template-file ./bicep/main.bicep 
        
        - name: Deploy Bicep
          if: success()
          id: deploy
          uses: Azure/arm-deploy@v1
          with:
            scope: resourcegroup
            resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
            template: ./bicep/main.bicep
            parameters: 
              environmentName=${{ env.ENVIRONMENT_NAME }}
              location=${{ env.AZURE_LOCATION }}
            failOnStdErr: false