name: Build and Deploy .NET Web App

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ job.status }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install npm packages
      working-directory: ./AzureWorkshopApp
      run: npm install

    - name: Restore dependencies
      run: dotnet restore

    - name: Echo build step
      run: echo "Now building the application..."

    - name: Build
      id: build
      run: dotnet build --configuration Release --no-restore
      
    - name: Run Tests
      if: success()
      uses: ./.github/workflows/test.yml

    - name: Publish
      if: success()
      run: dotnet publish ./AzureWorkshopApp/AzureWorkshopApp.csproj --configuration Release --output ./publish --no-build

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-azureskolen
        path: ./publish
        retention-days: 5

