# This workflow handles the deployment of our application to Azure Web App Service
# It's called by the main.yml workflow after build and login steps complete
name: Deploy to Azure

# Indicates this workflow can be called by other workflows
# This enables modular workflow design and reusability
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest    # Using Ubuntu for deployment tasks
    environment: test         # Links to GitHub Environment 'test' containing deployment variables
    
    steps:
    # Move Azure login step
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # First, retrieve the build artifacts that were created in the build job
    # These artifacts contain our compiled application ready for deployment
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app      # Must match the artifact name from build.yml
        path: ./publish       # Local path where artifacts will be downloaded

    # Deploy the application to Azure Web App
    # This step requires prior Azure authentication from 'Azure login step'
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}  # Name of your Azure Web App
        package: ./publish  