name: Deploy to Azure

env:
  ENVIRONMENT_NAME: ${{inputs.releaseType}}
  AZURE_LOCATION: 'norwayeast'
  RESOURCE_GROUP: 'rg-azskolen-${{inputs.releaseType}}'

on:
  workflow_dispatch: 
  workflow_call:
    inputs:
      releaseType:
        description: 'Where to release (test or prod)?'
        type: string
        required: true
        default: 'test'

permissions:
  contents: read
  id-token: write
  actions: read


jobs:
    validate-bicep:
      name: Validate Bicep
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Bicep lint
          uses: azure/cli@v1
          with:
            inlineScript: |
              set -e
              echo "Running Bicep build ..."
              az bicep build --file bicep/main.bicep
              echo "Running Bicep lint..."
              az bicep lint --file bicep/main.bicep

        - name: Bicep Validate
          if: success()
          uses: Azure/cli@v1
          with:
            inlineScript: |
              set -e
              echo "Validating Bicep template: rs-grp ${{env.RESOURCE_GROUP}}"
              az deployment group validate \
                --resource-group ${{ env.RESOURCE_GROUP }} \
                --template-file ./bicep/main.bicep \
                --parameters environment=${{ env.ENVIRONMENT_NAME }} location=${{ env.AZURE_LOCATION }}
        
        - name: What-If Deployment
          uses: azure/arm-deploy@v1
          with:
            scope: resourcegroup
            resourceGroupName: ${{ env.RESOURCE_GROUP }}
            template: ./bicep/main.bicep
            parameters: environment=${{ env.ENVIRONMENT_NAME }} location=${{ env.AZURE_LOCATION }}
            deploymentMode: Validate
            additionalArguments: --what-if
                
        - name: Deploy Bicep
          if: github.event_name == 'push' && github.ref == 'refs/heads/main'
          id: deploy
          uses: Azure/arm-deploy@v1
          with:
            scope: resourcegroup
            resourceGroupName: ${{ env.RESOURCE_GROUP }}
            template: ./bicep/main.bicep
            parameters: 
              environment=${{ env.ENVIRONMENT_NAME }}
              location=${{ env.AZURE_LOCATION }}
            failOnStdErr: false