name: Deploy to Azure

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app
        path: ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}
        package: ./publish
        slot-name: 'production'