name: Deploy to Azure

on:
  workflow_dispatch: 
  workflow_call:
    inputs:
      releaseType:
        description: 'Where to release (test or prod)?'
        type: string
        required: true
        default: 'TEST'

jobs:
  deploy:
    name: Deploy to ${{ inputs.releaseType }}
    environment: ${{ inputs.releaseType }}

    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: ./publish
          # slot-name: ${{ inputs.releaseType }}
