name: Deploy to Azure

on:
  workflow_call:
    inputs:
      releasetype:
        required: true
        type: string
        description: 'Environment to deploy to (test/production)'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.releasetype }}

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app-${{ inputs.releasetype }}
        path: ./publish    

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}-${{ inputs.releasetype }}
        package: ./publish
      
    - name: Azure Logout
      if: always()
      run: az logout
