name: IaC bicep validate

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    deploy-infrastructure:
      runs-on: ubuntu-latest
      env:
        RESOURCE_GROUP: your-resource-group-name
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Bicep lint
          uses: azure/cli@v1
          with:
            inlineScript: |
              az bicep build --file bicep/main.bicep
              az bicep lint --file bicep/main.bicep