name: IaC bicep validate

permissions:
  id-token: write
  contents: read
  pull-requests: write  # Add permission to write PR comments

env:
  ENVIRONMENT_NAME: 'TEST'
  AZURE_LOCATION: 'norwayeast'
  RESOURCE_GROUP_NAME: 'rg-azskolen-test'

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
    whatif-analysis:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Bicep lint
          uses: azure/cli@v1
          with:
            inlineScript: |
              az bicep build --file bicep/main.bicep
              az bicep lint --file bicep/main.bicep

        - name: Bicep Validate
          uses: Azure/cli@v1
          with:
            inlineScript: |
              az deployment group validate \
                --name validate-${{ github.run_id }} \
                --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
                --template-file ./bicep/main.bicep 
        
        - name: "What if"
          uses: Azure/cli@v1
          with:
            inlineScript: |
              az deployment group what-if \
                --name what-if-${{ github.run_id }} \
                --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
                --template-file ./bicep/main.bicep \
                --parameters environmentName=${{ env.ENVIRONMENT_NAME }} > whatif.json   


        - name: Deploy Bicep
          id: deploy
          uses: Azure/arm-deploy@v1
          with:
            scope: resourcegroup
            resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
            template: ./bicep/main.bicep
            parameters: 
              environmentName=${{ env.ENVIRONMENT_NAME }}
              location=${{ env.AZURE_LOCATION }}
            failOnStdErr: false