name: IaC bicep validate

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT_NAME: 'dev'
  AZURE_LOCATION: 'norwayeast'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    deploy-infrastructure:
      runs-on: ubuntu-latest
      outputs:
        resourceGroupName: ${{ steps.deploy.outputs.resourceGroupName }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Azure Login
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Bicep lint
          uses: azure/cli@v1
          with:
            inlineScript: |
              az bicep build --file bicep/main.bicep \
                --parameters environmentName=${{ env.ENVIRONMENT_NAME }} \
                --parameters location=${{ env.AZURE_LOCATION }}
              az bicep lint --file bicep/main.bicep

        - name: Deploy Bicep
          id: deploy
          uses: azure/arm-deploy@v1
          with:
            scope: subscription
            region: ${{ env.AZURE_LOCATION }}
            template: ./bicep/main.bicep
            parameters: 
              environmentName=${{ env.ENVIRONMENT_NAME }}
              location=${{ env.AZURE_LOCATION }}
            failOnStdErr: false