name: Infrastructure Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'bicep/**'
      - '.github/workflows/infrastructure.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  deploy-test-infra:
    name: Deploy Test Infrastructure
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'test'
    secrets: inherit

  deploy-prod-infra:
    name: Deploy Production Infrastructure
    needs: deploy-test-infra
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'production'
    secrets: inherit