name: CI/CD Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: [build]

  deploy-test:
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'TEST'  # input parameter
    secrets: inherit
    needs: [test]

  deploy-prod:
      uses: ./.github/workflows/deploy-azure.yml
      with:
        releaseType: 'production'
      secrets: inherit
      needs: [deploy-test] 