name: CI/CD Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: [build]

  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    needs: [build, test]