name: CI/CD Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: [build]

  deploy:
    uses: ./.github/workflows/deploy-azure.yml
    with:
      releaseType: 'test'  # input parameter
    secrets: inherit
    needs: [build, test]