name: Run Tests

on:
  workflow_call:  

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests with detailed logging
      run: |
        dotnet test AzureWorkshopAppTests/AzureWorkshopAppTests.csproj \
          --configuration Release \
          --no-restore \
          --verbosity detailed \
          --logger "console;verbosity=detailed" \
          --logger "trx;LogFileName=test-results.trx"

    - name: Upload test results
      if: always()  # Run this step even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/test-results.trx